# ===============================
#        application-dev.properties
#       (Development)
# ===============================

server.port=8080

# =========================
#        Oracle
# =========================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=ACADEMIC_PORTAL
spring.datasource.password=Oracle123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# Naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# =========================
#        JPA / Hibernate
# =========================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.default_schema=ACADEMIC_PORTAL
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true


#        Spring Data REST
# =========================
spring.data.rest.detection-strategy=annotated
springdoc.data-rest.enabled=false
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
springdoc.show-spring-data-rest=false

# =========================
#        Logging
# =========================
logging.level.root=INFO
logging.level.com.academic.portal=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.file.name=logs/app-dev.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7


# show all connection data
#spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
#spring.datasource.hikari.connection-timeout=30000
#logging.level.org.hibernate=DEBUG

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# =========================
#        Actuator / Monitoring
# =========================
management.endpoints.web.exposure.include=health,info,metrics,env,loggers
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=false

# =========================
#        Development Convenience
# =========================
spring.devtools.restart.enabled=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=true

# ========================
#        Constants
# ========================
app.dashboard-url=http://localhost:8080/swagger-ui/index.html#/


























