package com.academic.portal.enums;

public enum ResponseCode {
    // Auth
    USER_REGISTERED,
    ACCESS_TOKEN_REFRESHED,
    LOGIN_SUCCESS,
    LOGOUT_SUCCESS,

    // Users
    USER_UPDATED,
    USERS_FETCHED,
    USER_FETCHED,
    USER_CREATED,
    USER_DELETED,

    // Students
    STUDENTS_FETCHED,
    STUDENT_ADDED,
    STUDENT_UPDATED,
    STUDENT_FETCHED,
    STUDENT_DELETED,


    // Courses
    COURSES_FETCHED,
    COURSE_ADDED,
    COURSE_UPDATED,
    COURSE_FETCHED,
    COURSE_DELETED,

    // Course Registration
    COURSE_REGISTRATION_ADDED,
    COURSE_REGISTRATION_UPDATED,
    COURSE_REGISTRATION_FETCHED,
    COURSE_REGISTRATION_DELETED,
    REGISTRATION_CANCELED,





}
